[build]
base = "src/launcher-ui"
command = "npm run build"
publish = "build"


[dev]
command = "npm start"
functions = "netlify/functions"
edge_functions = "netlify/edge-functions"
port = 8888

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[edge_functions]]
function = "create-game"
path = "/create-game"

[[edge_functions]]
function = "create-team"
path = "/create-team"

[[edge_functions]]
function = "fetch-games"
path = "/fetch-games"

[[edge_functions]]
function = "get-user-games"
path = "/get-user-games"

[[edge_functions]]
function = "get-user-teams"
path = "/get-user-teams"

[[edge_functions]]
function = "github-app-auth"
path = "/github-app-auth"

[[edge_functions]]
function = "github-auth"
path = "/github-auth"

[[edge_functions]]
function = "update-game"
path = "/update-game"

[[edge_functions]]
function = "delete-game"
path = "/delete-game"

[[edge_functions]]
function = "delete-team"
path = "/delete-team"

[[edge_functions]]
function = "update-team"
path = "/update-team"

[[edge_functions]]
function = "verify-session"
path = "/verify-session"

[[edge_functions]]
function = "get-all-games"
path = "/get-all-games"