[build]
base = "src/launcher-ui"
command = "npm run build"
publish = "build"

[dev]
command = "npm start"
functions = "netlify/functions"
port = 8888

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
