[build]
base = "src/launcher-ui"
command = "CI=false npm run build"
publish = "build"


[dev]
command = "npm start"
functions = "netlify/functions"
edge_functions = "netlify/edge-functions"
port = 8888

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[edge_functions]]
function = "create-game"
path = "/create-game"

[[edge_functions]]
function = "create-team"
path = "/create-team"

[[edge_functions]]
function = "fetch-games"
path = "/fetch-games"

[[edge_functions]]
function = "get-user-games"
path = "/get-user-games"

[[edge_functions]]
function = "get-team-games"
path = "/get-team-games"

[[edge_functions]]
function = "get-user-teams"
path = "/get-user-teams"

[[edge_functions]]
function = "github-app-auth"
path = "/github-app-auth"

[[edge_functions]]
function = "github-auth"
path = "/github-auth"

[[edge_functions]]
function = "patreon-auth"
path = "/patreon-auth"

[[edge_functions]]
function = "connected-external-apps"
path = "/connected-external-apps"

[[edge_functions]]
function = "update-game"
path = "/update-game"

[[edge_functions]]
function = "delete-game"
path = "/delete-game"

[[edge_functions]]
function = "delete-team"
path = "/delete-team"

[[edge_functions]]
function = "update-team"
path = "/update-team"

[[edge_functions]]
function = "verify-session"
path = "/verify-session"

[[edge_functions]]
function = "get-all-games"
path = "/get-all-games"

[[edge_functions]]
function = "add-to-library"
path = "/add-to-library"

[[edge_functions]]
function = "remove-from-library"
path = "/remove-from-library"

[[edge_functions]]
function = "get-library-games"
path = "/get-library-games"

[[edge_functions]]
function = "get-user-quota"
path = "/get-user-quota"

[[edge_functions]]
function = "get-all-packages"
path = "/get-all-packages"

[[edge_functions]]
function = "get-package-by-id"
path = "/get-package-by-id"

[[edge_functions]]
function = "add-package"
path = "/add-package"

[[edge_functions]]
function = "update-package"
path = "/update-package"

[[edge_functions]]
function = "delete-package"
path = "/delete-package"
